# Generated by Django 3.2.9 on 2021-11-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0003_questionaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee_profile'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='related_Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
