# Generated by Django 3.2.9 on 2021-11-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0006_alter_projectmember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee_profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.questionaire')),
            ],
        ),
    ]
